### ISSUE TITLE
[FEATURE REQUEST]  Dark mode support

### ISSUE THREAD

**Issue by ndren** [mrdokenny/Cookie-AutoDelete#806]
**Is your feature request related to a problem? Please describe.**

I find that the extension has a significant impact on my eyes when setting grey/whitelists. I could not find any other issue related to this, so I thought it could be something to be considered.

**Describe the solution you'd like**

Implement a inverted or dark color scheme for the extension UI.

**Describe alternatives you've considered**

In theory, browsers have started support for natively changing the color scheme, but it is currently far from ready so it is unlikely to solve this issue.

**Additional context**

The inverted color scheme already looks [(somewhat) promising](https://ibb.co/7yc1RG5).

**Comment by kennethtran93** [comment]
This will need further research due to the way we're using bootstrap and react (importing from npm packages).

If anybody's up for it, this would (at a minimum) require
- a new setting in CAD Settings
- CSS overrides by className depending on above settings.
- All pages would need to be looked at (all settings pages and popup).

**Comment by ylor** [comment]
A new setting should be implemented but it CAD should default to the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media-query.

**Comment by kennethtran93** [comment]
> A new setting should be implemented but it CAD should default to the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media-query.

The docs currently states that it does not yet support Firefox Android (so in that sense a default would be needed anyway in our own configuration) . Also not sure how we would override that option through javascript if that setting is in the CSS.

**Comment by atomGit** [comment]
here's a quick-n-dirty dark theme (for the toolbar pop-up only) that the user can implement if desired

1. load `about:config` and set `toolkit.legacyUserProfileCustomizations.stylesheets` = `true`
2. create `userContent.css` in `/<your FF profile>/chrome` (create /chrome folder if it doesn't exist) and copy the example code below
3. load `about:debugging#/runtime/this-firefox` and replace `<EXT_ID>` in the CSS file with the UUID for CAD from the line `Internal UUID`

```css
@-moz-document url("moz-extension://<EXT_ID>/popup/popup.html") {
    body {
        color: white !important;
        background-color: black !important;
    }
    .card {
        color: white !important;
        background-color: #1e1e1e !important;
    }
    .table {
        color: white !important;
    }
    .table-hover tbody tr:hover {
        color: white !important;
    }
}
```

4. restart FF

**Comment by kennethtran93** [comment]
@atomGit That only applies to the individual user and not anything I can implement in code to push out to users.

**Comment by atomGit** [comment]
yes, sorry, that wasn't meant for you :)

**Comment by pablodekota** [comment]
> This will need further research due to the way we're using bootstrap and react (importing from npm packages).
> 
> If anybody's up for it, this would (at a minimum) require
> 
> * a new setting in CAD Settings
> * CSS overrides by className depending on above settings.
> * All pages would need to be looked at (all settings pages and popup).

ive tried doing it, but i almost had a stroke, due to how everything is setup, it is (atleast for me) very hard to do.

**Comment by sileeb** [comment]
Dark mode is BADLY needed.. its about time

**Comment by ghost** [comment]
My eyes.

**Comment by ElijahPepe** [comment]
For Bootstrap, I've found vinorodrigues' [Bootstrap Night](https://vinorodrigues.github.io/bootstrap-dark-5/examples/cheatsheet-night.html) as probably the most solid option for dark mode. Seems like all that needs to be done is to create a setting that would inject that CSS where it can and clear it when deselected.

**Comment by sileeb** [comment]
> For Bootstrap, I've found vinorodrigues' [Bootstrap Night](https://vinorodrigues.github.io/bootstrap-dark-5/examples/cheatsheet-night.html) as probably the most solid option for dark mode. Seems like all that needs to be done is to create a setting that would inject that CSS where it can and clear it when deselected.

I'm confused by your reply. What is bootstrap? And how can that make CAD go into dark mode?

.

**Comment by ElijahPepe** [comment]
1. Bootstrap is a CSS framework (and a bit more than that, but in this case just a CSS framework). It comes with its own design system, which can be adapted on since all HTML elements that Bootstrap supports are just that.
2. Bootstrap Night is a method to get Bootstrap with dark mode. It doesn't come with it by default, but Bootstrap Night looks nice and is just a CSS file, so it can be imported easily.

**Comment by sileeb** [comment]
How is bootstrap implemented for the CAD interface?

Theres a way to darken CAD through the app's UUID but its a bit of a pain especially when you refresh or create a new profile of firefox.

**Comment by ElijahPepe** [comment]
Bootstrap is implemented everywhere. It's imported via npm and everything in UI-related in the extension uses Bootstrap.

**Comment by sileeb** [comment]
> Bootstrap is implemented everywhere. It's imported via npm and everything in UI-related in the extension uses Bootstrap.

Never heard of bootstrap. How do I install it on firefox and darken CAD?

**Comment by ElijahPepe** [comment]
Bootstrap is included in CAD. To darken it you'd need to inject CSS into it.

**Comment by ghost** [comment]
We have working CSS for this (I'm sure it could use some attention to detail, but that's beside the point) is there some kind of hold-up here?

**Comment by sileeb** [comment]
> Bootstrap is included in CAD. To darken it you'd need to inject CSS into it.

I've looked everywhere for this bootstrap feature in the settings and couldnt find it. So I dont know what youre talking about.

**Comment by atomGit** [comment]
bootstrap is **not a feature** - it is **not exposed to the user** and (presently at least) you **cannot interact with it**

if you want to change the colors then one way to do so, without modifying the code, is outlined in my [earlier post](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/806#issuecomment-679201694)

**Comment by sileeb** [comment]
For all the ignorant "guys" on the thread regarding hair loss among trannys heres documentation. You can douse a male with estrogen all you want but his genetics will almost always trump. Read em and weep:

"Possible slowing or cessation of scalp hair loss, but no regrowth."

http://www.lgbthealtheducation.org/wp-content/uploads/2016/09/Tim-Cavanaugh_Cross-Sex-Hormone-Therapy.pdf

**Comment by sileeb** [comment]
Ok so now one user says bootstrap is included in CAD but youre saying its not. 

As for changing the colors your way, its not practical since you need to find out the UUID. Every browser has a different UUID for this addon. It becomes frustrating when you need to refresh firefox or create a new profile where you have to find the UUID yet again and start all over from scratch.

**Comment by sileeb** [comment]
> bootstrap is **not a feature** - it is **not exposed to the user** and (presently at least) you **cannot interact with it**
> 
> if you want to change the colors then one way to do so, without modifying the code, is outlined in my [earlier post](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/806#issuecomment-679201694)

Ok so now one user says bootstrap is included in CAD but youre saying its not. 

As for changing the colors your way, its not practical since you need to find out the UUID. Every browser has a different UUID for this addon. It becomes frustrating when you need to refresh firefox or create a new profile where you have to find the UUID yet again and start all over from scratch.

**Comment by atomGit** [comment]
where did i say it wasn't included?

**Comment by sileeb** [comment]
Read your last reply

**Comment by atomGit** [comment]
you quoted my reply for christ sake - where in did i say that bootstrap is **not included**? READ it again

**Comment by sileeb** [comment]
You asked me a question and I answered it. ACCEPT WHAT YOU REPLIED AND READ YOUR REPLY AGAIN

**Comment by kennethtran93** [comment]
@sileeb Bootstrap is included as part of our base CSS framework for styling and is what you see when you open the settings as well as the popup.  It is not a feature and there are no options exposed to the end user for configuration of it.  @atomGit is correct in that point.

Also for the time being, migrating to Bootstrap v5 will take some time as a few things we used will need to be adjusted.

**Comment by sileeb** [comment]
@atomGit said this: **"not exposed to the user and (presently at least) you cannot interact with it"**

Which he implies is NOT included in CAD so @Kennethtran93 is wrong.

**Comment by kennethtran93** [comment]
> @atomGit said this: **"not exposed to the user and (presently at least) you cannot interact with it"**
> 
> Which he implies is NOT included in CAD so @kennethtran93 is wrong.

Think we're just getting into technicalities here.  We're saying that 'not exposed to the user / can't interact with it' in terms of one cannot configure it to display/stylize something else (like a dark mode option) from the user setting.

Not exposed does not equal/imply not included.  An example of this would be the recent containerized cookie cleanup feature that wasn't available/exposed in the webextension API for Firefox browsers (up until recently) but the browser itself included the ability to remove those cookies by going through your browser preferences' cookies and site data window.

**Comment by KIMWW** [comment]
> here's a quick-n-dirty dark theme (for the toolbar pop-up only) that the user can implement if desired

@atomGit 
EXCELLENT, [the tricks works perfectly](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/806#issuecomment-679201694). Thank you.
I suppose it's possible to do it also with any other add-ons toolbar pop-up.
If so, what is the structure of the CSS file using a UUID from a different add-on? I tried a few different things but it did not work,,,

**Comment by ghost** [comment]
> I suppose it's possible to do it also with any other add-ons toolbar pop-up. If so, what is the structure of the CSS file using a UUID from a different add-on? I tried a few different things but it did not work,,,

It will be different for every addon.

**Comment by geedogz** [comment]
> > here's a quick-n-dirty dark theme (for the toolbar pop-up only) that the user can implement if desired
> 
> @atomGit EXCELLENT, [the tricks works perfectly](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/806#issuecomment-679201694). Thank you. I suppose it's possible to do it also with any other add-ons toolbar pop-up. If so, what is the structure of the CSS file using a UUID from a different add-on? I tried a few different things but it did not work,,,

I did EVERYTHING to make this work but it fails. What am I doing wrong?

I've used this technique before in other popups from other addons but I cant understand why this fails for CAD. Can someone help?

```
@-moz-document url("moz-extension://99fc54ae-0d32-486f-8fa0-a5a00b427d78/popup/popup.html") {
    body {
        color: white !important;
        background-color: black !important;
    }
    .card {
        color: white !important;
        background-color: #1e1e1e !important;
    }
    .table {
        color: white !important;
    }
    .table-hover tbody tr:hover {
        color: white !important;
    }
}
```

**Comment by Elaborendum** [comment]
I don't know what's wrong with it, but to add another workaround that may help for the time being, I've been using the theme from https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme (the CAD theme is in addons.css in the Full dark theme folder). It's pretty much a complete dark mode. It's unmaintained, but it still works.

Edit: I don't want to notify everyone, so I'll add this here. To clarify, while the linked project's main purpose is to make all of Firefox dark, it also has dark themes for some addons that don't touch anything but those addons. There's a theme specifically and solely for CAD in a section titled as such in the addons.css file.

**Comment by KIMWW** [comment]
> I did EVERYTHING to make this work but it fails. What am I doing wrong?

@geedogz 
Check that the folder "chrome" is all in small letters. At first it failed for me just because the folder was written "**C**hrome".

I've tried @atomGit [tricks](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/806#issuecomment-679201694) with other add-ons toolbar pop-up but unfortunately it does not work. Strangely enough it works only with CAD.

**Comment by geedogz** [comment]
> > I did EVERYTHING to make this work but it fails. What am I doing wrong?
> 
> @geedogz Check that the folder "chrome" is all in small letters. At first it failed for me just because the folder was written "**C**hrome".

I tried that but it doesnt work. I can now confirm since trying it on 2 different PCS that this code DOES NOT work at all. They likely changed something in ff  updates to prevent this from working.

Kenneth.. please add dark mode to CAD. Everyone's using dark mode and there shouldnt be an excuse not to implement it. Seriously its about time.

**Comment by geedogz** [comment]
> I don't know what's wrong with it, but to add another workaround that may help for the time being, I've been using the theme from https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme (the CAD theme is in addons.css in the Full dark theme folder). It's pretty much a complete dark mode. It's unmaintained, but it still works.

Looks like the suggestion atomGit provided isn't working for you either. 

Appreciate the link but I only want just one addon popup (CAD) to be darkened, not all my addon popups since a few of them I have already darkened through CSS and I dont want those superimposed by the addon you suggested.

**Comment by ghost** [comment]
The path on the CSS above may be your problem. This is the start of mine: (not showing the rest because I use variables and custom colours and it won't work at all for you... get the rest from above.)

``` 
@-moz-document url-prefix("moz-extension://e742cd38-2e27-45c2-88c4-bc30b7220ef7/") {
    body {
        .....
```

For the uninitiated: You can't just copy+paste this. That string of letters and numbers after moz-extension is unique to you and you'll have to find it. If you don't know how to do this, or it's not working, try to work it out and maybe ask r/firefoxcss for help, and post the answer here.

But please remember that everyone subscribed to this thread, likely including the author who's time you are asking for, gets a notification they have to go check, every time you post in here. As in, every time we post in here, we delay this feature. So let's try to not do that.

**Comment by geedogz** [comment]
Hey everyone.. it works now.  The only reason it didnt work before was cuz I applyed the code to the wrong firefox profile. I now applied it to the right one and everything works.

The only thing I'd like changed is the color of the element circled in red in the screen shot below. For unknown reasons, firefox wont let me inspect that element which is the blue link. If anyone knows the name of that link element let me know. 

![11](https://user-images.githubusercontent.com/69818302/175787840-90bb1b97-3f64-4971-bcb1-a4269070bd42.png)

**Comment by KIMWW** [comment]
Thanks for the hint @xcasxcursex.
With your CSS structure now I've managed to change 2 other add-ons toolbar pop-up as well.

@-moz-document **url-prefix**("moz-extension://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/")
**url-prefix**("moz-extension://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/"),
**url-prefix**("moz-extension://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/") {

    body {
        [...]

**Comment by misspent** [comment]
Made what the creator had in mind other than the top button background colors.
Use [this](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/806#issuecomment-679201694) as a guide to install this, thank you atomGit.

Sorry for reviving a “dead” post o_o
![Example](https://i.imgur.com/JN6MDA4.png)
```css
/* ======> Cookie Auto-Delete Extension <====== */ 
@-moz-document url-prefix("moz-extension://ffd6f1a4-a2cb-4673-81f9-d29bd181c7c8/") {
	/* atomGit edits */
body {
    color: white !important;
    background-color: black !important;
}
.card {
    color: white !important;
    background-color: #1e1e1e !important;
}
.table {
    color: white !important;
}
.table-hover tbody tr:hover {
    color: white !important;
}
	/* Misspent edits */
* {border-radius: 0px !important;}
.row.pt-2 {background: #101010 !important;}	
.row.justify-content-center.p-1 {background: #101010 !important; border-bottom: 1px solid #202020 !important;}
.btn {filter: brightness(85%) !important;} /* Makes BUTTONS darker */
/* Whitelist + Greylist Button */
.btn-secondary {color: black !important;}
.btn-secondary:hover {color: black !important;}
/* Whitelist button */
.btn-primary {
  color: black !important;
  background-color: orange !important;
  border-color: orange!important;
}
.btn-primary:hover {
  color: black !important;
  background-color: #ffa500d6 !important;
  border-color: #ffa500d6 !important;
}
.alert-primary {
  color: #a8d2ff !important;
  background-color: #3c5b79 !important;
  border-color: #3c5b79 !important;
}
.alert-danger {
  color: #f2a5ac !important;
  background-color: #792f35 !important;
  border-color: #792f35 !important;
}
/* Table */
.table-bordered td, .table-bordered th, .table thead th {
  border: 1px solid #282828 !important;
}
.table-striped tbody tr:nth-of-type(2n+1) {
  background-color: #101010 !important;
}
/* Matched domain expression text box */
.form-control-plaintext {
  color: #ccc !important;
  background: #151515 !important;
}
label:hover {
  background-color: #252525 !important;
}
/* Bottom cookie container */
.btn-link {color: orange !important;}
.btn-link:hover {color: #ffa500d6 !important;}
.card-header {
  background-color: #070707 !important;
  border-bottom: 1px solid #2d2d2d !important;
}
.btn-outline-danger {border-color: transparent !important;}
.collapse.show {background: #141414 !important;}
}
```
